[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/ricardojob/psae"
"Bug Tracker" = "https://github.com/ricardojob/psae/issues"